"""Create the two closed-loop phase portraits for the initial controller.

The script simulates trajectories of the controlled Van der Pol oscillator from
initial states in two rectangular computational domains and writes a PDF figure.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.patches as patches
import matplotlib.pyplot as plt
import numpy as np

from functions import auxFunctions, model, plotStyle


OUTPUT_FILE = Path("figures/initial_phase_portraits.pdf")


def initial_closed_loop_rhs(vdp_model: model.VanDerPol):
    """Return the closed-loop vector field generated by the initial feedback."""
    def rhs(state: np.ndarray) -> np.ndarray:
        """Evaluate the vector field at one two-dimensional state."""
        point   = np.atleast_2d(state).T
        control = vdp_model.stable_control(point)

        return vdp_model.closed_loop_rhs(point, control)[:, 0]

    return rhs


def plot_omega_a(ax, rhs) -> None:
    """Plot trajectories for the horizontal domain Omega_A."""
    dt         = 0.01
    end_time   = 10.0
    half_width = 0.25

    for x_index in range(25):
        for y_index in range(3):
            state      = np.array([1 - 2 * x_index / 24, half_width - 2 * half_width * y_index / 2])
            trajectory = auxFunctions.simulate_closed_loop(rhs, state, dt, end_time)
            ax.plot(trajectory[:, 0], trajectory[:, 1], color="C2", linewidth=0.62, alpha=0.95)

    domain_patch = patches.Rectangle(
        (-1, -0.25),
        2,
        0.5,
        facecolor = "grey",
        edgecolor = "none",
        alpha     = 0.5,
        zorder    = 0,
    )
    ax.add_patch(domain_patch)


def plot_omega_b(ax, rhs) -> None:
    """Plot trajectories for the vertical domain Omega_B."""
    dt         = 0.01
    end_time   = 10.0
    half_width = 0.25

    for y_index in range(15):
        for x_index in range(5):
            state      = np.array([half_width - 2 * half_width * x_index / 4, 1 - 2 * y_index / 14])
            trajectory = auxFunctions.simulate_closed_loop(rhs, state, dt, end_time)
            ax.plot(trajectory[:, 0], trajectory[:, 1], color="C2", linewidth=0.62, alpha=0.95)

    domain_patch = patches.Rectangle(
        (-0.25, -1),
        0.5,
        2,
        facecolor = "grey",
        edgecolor = "none",
        alpha     = 0.5,
        zorder    = 0,
    )
    ax.add_patch(domain_patch)


def format_phase_axis(ax) -> None:
    """Apply the shared axis formatting for a phase-portrait panel."""
    ax.set_xlabel(r"$x$")
    ax.set_ylabel(r"$y$")
    ax.set_xlim(-1.1, 1.1)
    ax.set_ylim(-1.1, 1.1)
    ax.set_xticks(np.linspace(-1, 1, 5))
    ax.set_yticks(np.linspace(-1, 1, 9))
    ax.set_aspect("equal")
    ax.grid(True, which="major", alpha=0.6, linewidth=0.8)
    ax.set_axisbelow(True)


def plot_initial_phase_portraits(output_file: Path = OUTPUT_FILE) -> Path:
    """Create and save the two-panel initial-controller phase portrait."""
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with plt.rc_context(plotStyle.rc_parameters()):
        vdp_model = model.VanDerPol(1, 1 / 50)
        rhs       = initial_closed_loop_rhs(vdp_model)
        fig, axes = plt.subplots(1, 2, figsize=(6.5, 3.1), constrained_layout=True)

        plot_omega_a(axes[0], rhs)
        plot_omega_b(axes[1], rhs)

        for axis in axes:
            format_phase_axis(axis)

        fig.savefig(output_file, bbox_inches="tight", dpi=plotStyle.FIGURE_DPI)
        plt.close(fig)

    return output_file


def main() -> None:
    """Run the script from the command line."""
    path = plot_initial_phase_portraits()
    print(f"Saved {path}")


if __name__ == "__main__":
    main()
